<Project Sdk="MSTest.Sdk/3.7.3">

  <PropertyGroup>
    <AssemblyName>bimil.core.internal.tests</AssemblyName>
    <RootNamespace>Tests</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Bimil.Core/Bimil.Core.csproj" />
  </ItemGroup>

</Project>
