#!/bin/sh -e

# Show dialog if repository is not there
SOURCE_FILE="/etc/apt/sources.list.d/medo64.list"
if ! [ -f "$SOURCE_FILE" ] && [ "$DEBIAN_FRONTEND" != "noninteractive" ]; then
    . /usr/share/debconf/confmodule

    db_input high bimil/add_repository
    db_go
    db_get bimil/add_repository
    case "$RET" in
        n*|N*|f*|F*) DO_ADD_REPO=0 ;;
    esac
fi

DO_ADD_REPO=0
SOURCE_FILE="/etc/apt/sources.list.d/medo64.list"
if ! [ -f "$SOURCE_FILE" ] && [ "$DEBIAN_FRONTEND" != "noninteractive" ]; then
    . /usr/share/debconf/confmodule
    db_get bimil/add_repository
    case "$RET" in
        y*|Y*|T*|t*) DO_ADD_REPO=1 ;;
    esac
fi

if [ "$DO_ADD_REPO" -ne 0 ]; then
    echo "deb https://medo64.com/repositories/deb stable main" > "$SOURCE_FILE"
    echo "-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFqxbGoBCACnavHwueNmk947TOkLDsnay/4uQIan79YFyHnv2zTFRuszuwFw
65sbflaBTjR57CZRzNyXHEcPb/NrxxuhXKHOXzbURy6FBv0CQZVjf9bm0Lroq5Ab
oZ9v0UZukpLoAyHkNca/zyHJoHtAq2Deq5X44dPRsCALn2zWJKya+hyA8ZYnGlcG
hERdnR8mMB+i0xb44rnDNY7GwdRykSialn3WopSFBrHv9pYOd2wtnrb3H9pFjT3H
jNp1+3/4mW6WDdVzC7mkJk9ia8mHqAw0IgtE7fP7HYcJnmdqCqgI3sZBR+D1VpyM
CgNGK6DrGD5IUp1ktZe2wAL8Jig2/Xmk02g7ABEBAAG0L0pvc2lwIE1lZHZlZCAo
UmVwb3NpdG9yeSkgPGptZWR2ZWRAam1lZHZlZC5jb20+iQE4BBMBCAAiBQJasWxq
AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRA4LnS5Ecf8hgj0B/0XeXn8
aPkDLwHJzLbily9SUxn3WYcZhXEE1JSXtDHWI1owS/TT7kZxswHRh1DyZDQJSK0B
LCsHx1zoIVIvlkGz8PNfN+G/E+2CAI8/cdDBa5z8DM+w8wpQ02NZjWnS5pmpr3MT
sP7hLlyEeq/ErtKmZMlquDtTR7lUjundgtUIgofiSDiri/1xNynUmPgykkKR/vR2
mrPHCxIqiEEq5RkFvIDpH6zltld97AeNP2vEcmkpyS9npFRkHgPNjxZhvHhhjbHP
pXF542bTCX+bXOfPWbdl/mnIBRKdsNGNu/FbXTQ4gEmXQwmki5YL8kRwbBloxuH2
5VcfjRkkgrnxUy4S
=gY4j
-----END PGP PUBLIC KEY BLOCK-----" | apt-key add -
fi

# Done
exit 0
