#!/bin/bash
set -e

chmod +x /opt/bimil/bimil
rm "/usr/bin/bimil" 2>/dev/null || true
ln -s /opt/bimil/bimil /usr/bin/bimil

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
