#!/bin/bash
set -e

# Remove link
if [ "$1" == "remove" ]; then
    if [ -f "/usr/bin/bimil" ]; then
        rm "/usr/bin/bimil"
    fi

    if [ -f "$HOME/.bimil" ]; then
        rm "$HOME/.bimil"
    fi
fi

# Purge debconf
if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

# Done
exit 0
